### ISSUE TITLE
magento 1.9.1

### ISSUE THREAD

**Issue by ljuboja** [gaiterjones/magento-minifyhtml#1]
Is it working with  1.9.1 version?

Tnx

**Comment by gaiterjones** [comment]
Yes.

**Comment by ljuboja** [comment]
Great, but I still got problem. I can't see htmlminify in backend. I copied code, log out, clear cache and nothing.

**Comment by gaiterjones** [comment]
OK, I need to look into that then…

**Comment by gaiterjones** [comment]
I can reproduce this, seems to be a permissions problem with the module, but I haven't found the cause of the problem yet.... If you look in user roles, you won't see the module listed which is why it doesn't show in the admin even though the module is enabled. The only option in the admin section is to enable or disable the minify, its disabled by default, If you want to manually enable it, edit the source code.

**Comment by gaiterjones** [comment]
Fixed.

**Comment by allinvinod** [comment]
Hi,
I have installed this extension, then the ajax login working is not processed. customer login but ajax login window not closed.
Please suggest the solution. 

Thanks & Regards
Vinod Kumar
